services:
  app:
    platform: "linux/amd64"
    container_name: wai-wss
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
  redis:
    platform: "linux/amd64"
    container_name: wai-redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  redis:
    external: false
    